# Generated by Django 2.2.6 on 2019-10-19 21:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('card_id', registry.models.NullCharField(blank=True, default=None, max_length=20, null=True, unique=True)),
                ('discord_id', registry.models.NullCharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('ldap_uid', registry.models.NullCharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('tshirt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=32, unique=True)),
                ('secret', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(blank=True, to='registry.Role')),
            ],
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CARD', 'Card'), ('LDAP', 'LDAP'), ('DISCORD', 'Discord'), ('EMAIL', 'Email')], default='CARD', max_length=10)),
                ('value', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to='registry.Client')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to='registry.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='registry.Member')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='registry.Period')),
                ('roles', models.ManyToManyField(related_name='memberships', to='registry.Role')),
            ],
            options={
                'unique_together': {('member', 'period')},
            },
        ),
    ]
