# Generated by Django 3.1.2 on 2020-10-09 18:49

from django.db import migrations, models
import selfservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfservicetoken',
            name='token',
            field=models.CharField(default=selfservice.models._random_token, max_length=64),
        ),
    ]
